### PR TITLE
Show child windows

### PR DESCRIPTION
**Pull request by jeremypw**
see https://github.com/elementary/screenshot-tool/issues/1

This branch provides a solution to the problem of including popups and menus in a snapshot of a current window. Instead of using pixbuf_get_from_window, the same method as used for grabbing selected areas is used - that is obtaining a subpixbuf from the whole window - after calculating a suitable selection rectangle.

This is complicated by the fact that window.get_frame_extents includes any border around the main window area used to show shadows etc. The function that discounts this relies on it having a low opacity compared with the rest of the window. The method therefore relies on the pixbufs obtained will have four channels per pixel with one byte per channel. It is not known whether changing to Wayland will affect this.

The final screenshot is a composite of both methods in order that the window shadow and non-CSD decorations are included (if present).

It is recognized that this solution is "hacky" so if a simpler solution is available it should be preferred.

If the current window is partially off the current screen any menus or popups extending outside the main window will be truncated (as they are not drawn by the current window).

Testing on a hi-DPI as well as a standard display is desirable.

### CODE REVIEW

**Comment by jeremypw** [comment]
I have reverted changes not related to showing child windows.  They will be the subject of future branches.

**Comment by danrabbit** [comment]
It looks like this branch now conflicts with master

**Comment by danrabbit** [comment]
Looks like this branch also captures the wallpaper behind transparent windows

With master:
screenshot from 2017-05-05 09 51 30

With this branch:
screenshot from 2017-05-05 09 50 51

**Comment by jeremypw** [comment]
The branch after resolving conflicts with the current master needs particular testing with respect to real HiDPI displays especially in relation to cursor positioning and size. A previous branch addressing this has been reverted as it was incompatible with the changes made by this branch.  However, this branch should fix the same issues.  This branch has been tested on an ordinary display with the scale factor turned up to 2.

**Comment by jeremypw** [comment]
The effect on transparent windows was recognized but I was unable to find a straightforward way of capturing tooltips/menus etc without this side-effect.  It may be possible by delving deeply into the window manager but I do not have the necessary knowledge at the moment. One mitigation would be to make child window capture a fourth option, so the existing behaviour can be retained for transparent windows.

**Comment by cassidyjames** [comment]
I guess that'd be up to @elementary/ux then?

**Comment by jeremypw** [comment]
Closed pending better solution.

**Pull request closed without merging**
