### PR TITLE
Get preview image at scale

### PR DESCRIPTION
**Pull request by danrabbit**
Gotta be tested on LoDPI

### CODE REVIEW

**Comment by cassidyjames** [comment]
Can confirm something screwy is happening here on LoDPI. The screenshot is not centered and the box has shadow around it.

**Comment by danrabbit** [comment]
The shadow is intentional. Can you provide more details? I'm not sure what your screenshot is intended to look like, so it's hard to figure out what went wrong

**Comment by artemanufrij** [comment]
@danrabbit only the small rectangle on the left side (ca. 1cm).

**Comment by cassidyjames** [comment]
Here's a photo I took of the screenshot tool (in front of the window I screenshotted). The preview is not centered and the shadow looks confusing. The checkerboard bg would help but there's still something going on with the alignment. :)

photo

**Pull request merged**
