### PR TITLE
Add .desktop and appdata validation tests

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by jeremypw** [comment]
When run locally, both tests fail - the desk-top-file and appdata file fail validation.

Presumably this PR cannot be merged until the new tests are made to pass?

**Comment by jeremypw** [comment]
Note that the Travis CI failures are for a different reason - the files to be tested were not found. It is noted that the Travis build directory is "build-dir" whereas locally it is "build". Not sure if this is significant.

**Comment by danrabbit** [comment]
Yep, marking as "blocked" since these tests are currently failing

**Comment by danrabbit** [comment]
Closing since I'll revisit this after meson

**Pull request closed without merging**
